### PR TITLE
Hello-world VID integration

### LINKED ISSUE #1662: T1: Hello-world VID integration: copy DA committee workflow
Many subtasks. See issues linked to PR #1684

### LINKED ISSUE #1713: VID tests take way too long
CI fails due to timeout. See for example [this run](https://github.com/EspressoSystems/HotShot/actions/runs/6148772200/job/16683219470?pr=1684)

### PR DESCRIPTION
**Pull request by ggutoski**
close #1662 

VID "integration" is really just a clone of DA committee. New events, msg types, etc for VID that mirror DA events msg types, etc. Lots of code copied blindly from DA committee that will need to be revisited in the future.

## TODO before merge

- [x] Post github issues for all the `TODO GG` code comments, then link to those issues in the `TODO GG` comments.
- [x] Fix #1713

### CODE REVIEW

File: crates/task-impls/src/consensus.rs [hunk 1]
```diff
@@ -1034,7 +1034,17 @@ where
                     self.update_view(view + 1).await;
                 }
             }
+            SequencingHotShotEvent::VidCertRecv(cert) => {
+                debug!("VID cert received for view ! {}", *cert.view_number);
 
+                let view = cert.view_number;
+                self.certs.insert(view, cert);
```
Comment (elliedavidson) [inline crates/task-impls/src/consensus.rs:1041]: Currently `self.certs` stores the DAC type.  We should probably update it to store both the VIDCert type and DAC type.

File: crates/task-impls/src/da.rs [hunk 2]
```diff
@@ -192,8 +192,59 @@ where
...
+                        .await;
+
+                    // Return completed at this point
+                    return (Some(HotShotTaskCompleted::ShutDown), state);
+                }
+            }
+        }
         SequencingHotShotEvent::Shutdown => return (Some(HotShotTaskCompleted::ShutDown), state),
-        _ => {}
+        _ => {} // TODO GG error log here?
```
Comment (elliedavidson) [inline crates/task-impls/src/da.rs:247]: Yes, we should put an error there!

File: crates/task-impls/src/events.rs [hunk 3]
```diff
@@ -62,4 +62,30 @@ pub enum SequencingHotShotEvent<TYPES: NodeType, I: NodeImplementation<TYPES>> {
...
     SendDABlockData(TYPES::BlockType),
+    /// Send VID shares to VID storage nodes; emitted by the DA leader
+    ///
+    /// Like [`DAProposalSend`].
+    VidDisperseSend(VidDisperse<TYPES>, TYPES::SignatureKey),
+    /// Vid disperse data has been received from the network; handled by the DA task
+    ///
+    /// Like [`DAProposalRecv`].
+    /// TODO GG: lots of boilerplate here eg. `VidDisperse[Send|Recv]`. If we need both [Send|Recv] then maybe partition [`SequencingHotShotEvent`] into separate enums?
+    /// TODO GG: should [`VidDisperse`] be of the form [`Proposal<DAProposal<TYPES>>`] to mirror [`DAProposalRecv`]? We need things like `Committable`, etc.
```
Comment (elliedavidson) [inline crates/task-impls/src/events.rs:73]: It probably should, but also we need to revisit those traits - we are outgrowing them.  I ran into a similar issue with the timeout certificate logic where the exchange trait is too restrictive.  And the ViewSync logic works with those traits, but is a bit of a square peg in a round hole.

File: crates/task-impls/src/network.rs [hunk 4]
```diff
@@ -186,6 +195,7 @@ impl<
     /// Returns the completion status.
     /// # Panics
     /// Panic sif a direct message event is received with no recipient
+    #[allow(clippy::too_many_lines)] // TODO GG we should probably do something about this
```
Comment (elliedavidson) [inline crates/task-impls/src/network.rs:198]: Yes, I very much agree.

File: crates/task-impls/src/network.rs [hunk 5]
```diff
@@ -211,6 +221,15 @@ impl<
                 Some(membership.get_leader(vote.current_view() + 1)),
             ),
 
+            // TODO GG `VidDiserpseSend` like `DAProposalSend` for now
+            SequencingHotShotEvent::VidDisperseSend(proposal, sender) => (
+                sender,
+                MessageKind::<TYPES, I>::from_consensus_message(SequencingMessage(Right(
+                    CommitteeConsensusMessage::VidDisperseMsg(proposal),
+                ))), // TODO GG not a CommitteeConsensusMessage
+                TransmitType::Broadcast, // TODO GG broadcast??
```
Comment (elliedavidson) [inline crates/task-impls/src/network.rs:230]: This is an interesting case.  We'll want to only send 1 message to upload the shares to the CDN, but we'll need to "directly" message peers through libp2p to send each node their own unique share.  We should discuss more what the best way to do this is; I haven't given it much thought at the moment.  Perhaps the easiest solution is to handle the VID disperse message differently depending on which network implementation it is being routed through.  We can maybe use `MessagePurpose` for this.

File: crates/types/src/message.rs [hunk 6]
```diff
@@ -396,8 +445,12 @@ impl<
             },
             Right(committee_message) => match committee_message {
                 CommitteeConsensusMessage::DAProposal(_) => MessagePurpose::Proposal,
-                CommitteeConsensusMessage::DAVote(_) => MessagePurpose::Vote,
+                CommitteeConsensusMessage::DAVote(_) | CommitteeConsensusMessage::VidVote(_) => {
```
Comment (elliedavidson) [inline crates/types/src/message.rs:448]: Due to some tech debt in the web server design, the VidVote will need to have it's own message purpose so the web server can differentiate it from a QuorumVote.

**Review by elliedavidson — COMMENTED** [review]
I left some comments just to potentially help with the work - nothing you need to actively address.

File: crates/task-impls/src/events.rs (hunk 3 above)
Comment (ggutoski) [reply crates/task-impls/src/events.rs:73]: new issue https://github.com/EspressoSystems/HotShot/issues/1694

File: crates/task-impls/src/network.rs (hunk 5 above)
Comment (ggutoski) [reply crates/task-impls/src/network.rs:230]: oh yes this is going to be painful. new issue https://github.com/EspressoSystems/HotShot/issues/1696

File: crates/task-impls/src/consensus.rs (hunk 1 above)
Comment (ggutoski) [reply crates/task-impls/src/consensus.rs:1041]: new issue https://github.com/EspressoSystems/HotShot/issues/1701

File: crates/types/src/message.rs (hunk 6 above)
Comment (ggutoski) [reply crates/types/src/message.rs:448]: new issue https://github.com/EspressoSystems/HotShot/issues/1702

File: crates/task-impls/src/network.rs (hunk 4 above)
Comment (ggutoski) [reply crates/task-impls/src/network.rs:198]: new issue https://github.com/EspressoSystems/HotShot/issues/1704

**Review by bfish713 — APPROVED** [review]

File: crates/testing/tests/da_task.rs [hunk 7]
```diff
@@ -80,7 +87,20 @@ async fn test_da_task() {
...
+            VidDisperse {
+                view_number: message.data.view_number,
+                shares,
+                common,
+            },
+            pub_key,
+        ),
+        1,
+    );
+    // TODO why does this test pass without a `VidVoteSend` event here? https://github.com/EspressoSystems/HotShot/issues/1697
```
Comment (shenkeyao) [inline crates/testing/tests/da_task.rs:101]: Have you tried adding `VidVoteSend` to `output`? This test terminates once all the expected outputs are received, so maybe it terminates before getting `VidVoteSend`, which isn't in `output`.

**Review by shenkeyao — APPROVED** [review]
Looks good! I left some nit comments, and some explanations to your questions in the DA and network test files.

File: Cargo.toml [hunk 8]
```diff
@@ -61,53 +61,54 @@ nll = { git = "https://github.com/EspressoSystems/nll.git" }
...
-    "request-response",
-    "rendezvous",
-    "secp256k1",
-    "serde",
-    "tcp",
-    "uds",
-    "wasm-ext",
-    "websocket",
-    "yamux",
+        "macros",
```
[the remark this answers is not in the document]
Comment (ggutoski) [reply Cargo.toml:72]: Yes auto format. I don't even know which of my vscode extensions does it. Do you have a recommended extension?

File: crates/task-impls/src/da.rs [hunk 9]
```diff
@@ -412,6 +464,172 @@ where
...
+                // `self.cur_view` should be at least 1 since there is a view change before getting
+                // the `DAProposalRecv` event. Otherewise, the view number subtraction below will
+                // cause an overflow error.
+                if view < self.cur_view - 1 {
+                    warn!("Throwing away VID disperse data that is more than one view older");
+                    return None;
+                }
+
+                debug!("VID disperse data is fresh.");
+                // TODO https://github.com/EspressoSystems/jellyfish/issues/369
```
[the remark this answers is not in the document]
Comment (ggutoski) [reply crates/task-impls/src/da.rs:575]: Sounds good. Let's punt this to a future PR though.

File: crates/task-impls/src/da.rs [hunk 10]
```diff
@@ -192,8 +192,61 @@ where
...
+            debug!("VID vote recv, collection task {:?}", vote.current_view);
+            // panic!("Vote handle received DA vote for view {}", *vote.current_view);
+
+            // For the case where we receive votes after we've made a certificate
+            if state.accumulator.is_right() {
+                debug!("VID accumulator finished view: {:?}", state.cur_view);
+                return (None, state);
+            }
+
+            let accumulator = state.accumulator.left().unwrap();
```
[the remark this answers is not in the document]
Comment (ggutoski) [reply crates/task-impls/src/da.rs:206]: done in 864656f2e243739405548dc51be0574d8f992b41

File: crates/testing/tests/network_task.rs [hunk 11]
```diff
@@ -74,6 +88,10 @@ async fn test_network_task() {
         SequencingHotShotEvent::DAProposalSend(da_proposal.clone(), pub_key),
         2,
     );
+    output.insert(
+        SequencingHotShotEvent::VidDisperseSend(da_vid_disperse, pub_key),
+        2, // TODO why 2 here and not 1 like everywhere else?
```
[the remark this answers is not in the document]
Comment (ggutoski) [reply crates/testing/tests/network_task.rs:93]: done in 8bf7861ddab07dc53cffafaa034bc99f060a1b55

File: crates/testing/tests/da_task.rs [hunk 12]
```diff
@@ -80,7 +87,20 @@ async fn test_da_task() {
...
     output.insert(SequencingHotShotEvent::DAProposalRecv(message, pub_key), 1);
+    // TODO why does this test pass without a `VidDisperseRecv` event here? https://github.com/EspressoSystems/HotShot/issues/1697
```
[the remark this answers is not in the document]
Comment (ggutoski) [reply crates/testing/tests/da_task.rs:103]: In that case, why does this test need a `DAProposalRecv` event in the output but not a `VidDisperseRecv`? I expect either both are needed or neither.

File: crates/testing/tests/da_task.rs (hunk 7 above)
Comment (ggutoski) [reply crates/testing/tests/da_task.rs:101]: I tried adding `VidVoteSend` to `output`. The test hangs when I do that. Seems that there's something wrong in the way I've copied the VID vote code from DA vote.

File: Cargo.toml (hunk 8 above)
[the remark this answers is not in the document]
Comment (shenkeyao) [reply Cargo.toml:72]: No good one that I'm aware of. ☹️ The extension I used to have didn't work nicely. It ordered and formatted dependencies in a weird way, so I disabled it.

File: crates/testing/tests/da_task.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (shenkeyao) [reply crates/testing/tests/da_task.rs:103]: Though neither of them is sent by the DA task, `DAProposalRecv` is in the input, so it will also be in the output. If we don't have `DAProposalRecv` in the input, then indeed, it won't be expected in the output.

**Comment by ggutoski** [comment]
# Status

[CI currently fails](https://github.com/EspressoSystems/HotShot/actions/runs/6161101122/job/16719555061?pr=1684) as follows:

## `web_server_network` (aka `test_web_server`)
```
Results: [("Test Overall Safety Task", NotEnoughDecides { expected: 35, got: 31 })]
```
and many copies of
```
  2023-09-12T15:03:40.028829Z ERROR hotshot_task_impls::network: Failed to send message from network task: WebServer { source: ClientError }
    at crates/task-impls/src/network.rs:320
```
This test succeeds on my local machine but I do see these same error logs.

## `test_success`
```
Results: [("Test Overall Safety Task", NotEnoughDecides { expected: 50, got: 24 })]
```
and 5 copies of the following log
```
2023-09-12T15:00:21.508290Z ERROR hotshot_types::traits::election: Leaf commitment does not equal parent commitment
    at crates/types/src/traits/election.rs:353
    in hotshot_task_impls::consensus::Consensus vote if able with id: 4, view: 26
    in hotshot_task_impls::consensus::Consensus replica task with id: 4, view: 26

  2023-09-12T15:00:21.508723Z ERROR hotshot_task_impls::consensus: Invalid DAC in proposal! Skipping proposal. ViewNumber(26) cur view is: ViewNumber(26)
    at crates/task-impls/src/consensus.rs:440
    in hotshot_task_impls::consensus::Consensus vote if able with id: 4, view: 26
    in hotshot_task_impls::consensus::Consensus replica task with id: 4, view: 26
```
Strangely, this test passes quite quickly on my local machine with *no error logs*. Wha....???

File: crates/testing/tests/da_task.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (ggutoski) [reply crates/testing/tests/da_task.rs:119]: I see. Indeed, the test passes if I add `VidDisperseRecv` to both `input` and `output`. But what's the point? Do these additions hit any new code paths? Would the test still function correctly if I were to delete both `VidDisperseRecv` and `DAProposalRecv` from both `input` and `output`?

File: crates/testing/tests/da_task.rs (hunk 7 above)
Comment (ggutoski) [reply crates/testing/tests/da_task.rs:108]: Solved. I need to add `VidDisperseRecv` to both `input` and `output`. Then the test no longer hangs when I add `VidVoteSend` to `output`.

File: crates/testing/tests/da_task.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (ggutoski) [reply crates/testing/tests/da_task.rs:119]: I think the answer is that `VidVoteSend` does not appear unless `VidDisperseRecv` is in `input` and `output`. In other words, if `VidDisperseRecv` is missing then we do not test VID votes. I suspect the same is true for `DAProposalRecv` and `DAVoteSend`. See https://github.com/EspressoSystems/HotShot/pull/1684#discussion_r1323512874

**Comment by ggutoski** [comment]
Commit https://github.com/EspressoSystems/HotShot/pull/1684/commits/d3dbbdc510bea683ff092e76406719e5c5e5228c raised the timeout limit for `test_success` and `test_web_server`. All tests pass in [CI for that commit](https://github.com/EspressoSystems/HotShot/actions/runs/6162436783/job/16723904288). (CI still failed, but this time it's a docker problem.) Indeed, this CI run of `test_success` had zero error logs (matching behaviour on my local machine), and `test_web_server` emitted the same error logs described [above](https://github.com/EspressoSystems/HotShot/pull/1684#issuecomment-1716002508). I don't know why `test_success` emitted zero error logs in CI this time. Strange.

**Comment by ggutoski** [comment]
I now think we have nondeterministic behaviour that sometimes causes tests to fail:
- exhibit A: [the previous CI run](https://github.com/EspressoSystems/HotShot/actions/runs/6167692991/job/16739030233) fails `test_catchup` in the tokio build.
- exhibit B: A single run of `test_web_server` on my local machine (with `ASYNC_STD_THREAD_COUNT=1`) emitted a million scary error logs and ran for a very long time. But I cannot reproduce it. (Unfortunately I did not copy the logs for that run before they were discarded.)

**Comment by ggutoski** [comment]
Candidate final commit for this PR: https://github.com/EspressoSystems/HotShot/pull/1684/commits/2c5672285edb21fb57b69b40788f9c9e7dce6852
Tests pass but then docker fails -> same behaviour as described [above](https://github.com/EspressoSystems/HotShot/pull/1684#issuecomment-1716915584)
