### PR TITLE
Fix libp2p examples

### LINKED ISSUE #1545: Update examples to work with libp2p
Copy [web server](https://github.com/EspressoSystems/HotShot/tree/main/examples/web-server-da) style to work with [libp2p](https://github.com/EspressoSystems/HotShot/tree/main/examples/libp2p). This will require implementation of a new struct mirroring [web server](https://github.com/EspressoSystems/HotShot/blob/0fea552d3eca281a64afc06837d3c830931c9b6c/examples/infra/modDA.rs#L451) that also implements [RunDA](https://github.com/EspressoSystems/HotShot/blob/0fea552d3eca281a64afc06837d3c830931c9b6c/examples/infra/modDA.rs#L509).

### PR DESCRIPTION
**Pull request by rob-maron**
aims to close #1545

### CODE REVIEW

File: crates/hotshot/examples/infra/modDA.rs [hunk 1]
```diff
@@ -720,3 +1019,13 @@ pub async fn main_entry_point<
     info!("All nodes are ready!  Starting HotShot");
     run.run_hotshot(hotshot).await;
 }
+
+/// yeesh maybe we should just implement SignatureKey for this...
```
Comment (DieracDelta) [inline crates/hotshot/examples/infra/modDA.rs:1023]: This comment can likely be deleted. iirc SignatureKey is slated for deprecation

**Review by DieracDelta — APPROVED** [review]
Great work, this LGTM!

**Review by DieracDelta — DISMISSED** [review]

**Review by DieracDelta — DISMISSED** [review]

**Comment by elliedavidson** [comment]
Let's merge this today so we can start benching, and make issues for anything outstanding.

**Review by elliedavidson — APPROVED** [review]
